import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";

import { ThemeProvider } from "@/components/ui/theme-provider";

//App navbar
import NavBar from "@/components/custom/NavBar";
//footer
import Footer from "@/components/custom/Footer";
//Layout with recoil
import Layout from "@/components/custom/Layout";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Green Ion",
  description: "Generated by Green Ion",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Layout>
            <NavBar />
            {children}
          </Layout>
        </ThemeProvider>
        <Footer />
      </body>
    </html>
  );
}
